### ISSUE TITLE
Investigate what blockchain we should use to take payments

### ISSUE THREAD

**Issue by jacobmeredith** [choggy-side-projects/crypto-marketplace#11]
# Description
Have a look through the potential options for payment methods. The choice must allow us to test with a fake balance.

- Potential options
  - Solana

**Comment by NakxH** [comment]
I have done some research and I believe that Solana is the best route to go down. Solana allows us to utilise the Solana Devnet to test transactions. Moreover, Solana's network is fast, reliable and economically viable when the app is released.
